all:
  children:
    controllers:
      hosts:
        ansible:
          ansible_connection: local

    debian:
      hosts:
        borg:
          ansible_host: borg 

    vps:
      hosts:
        codemachine:
          amsible_host: codemachine
          docker_host: true

        freevps:
          ansible_host: freevps 
