all:
  children:

    controllers:
      hosts:
        ansible:
          ansible_connection: local

    siem:
      hosts:
        syslog:
          ansible_host: siem
          ansible_user: admin

    debian_servers:
      hosts:
        borg:
          ansible_host: borg

        mediavm:
          ansible_host: mediavm

    vps:
      hosts:
        codemachine:
          ansible_host: codemachine

        freevps:
          ansible_host: freevps
