---
- name: Restart ssh
  service:
    name: ssh
    state: restarted

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Apply sysctl
  command: sysctl --system

- name: Restart docker
  service:
    name: docker
    state: restarted
